### ISSUE TITLE
How to effectively access related database

### ISSUE THREAD

**Issue by UboCA** [pachterlab/gget_examples#1]
Hi, gget build team.

I met SSLerror after running a series of gget commands as follows:

```
Traceback (most recent call last):
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/shpc_100692/miniconda3/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/shpc_100692/miniconda3/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/shpc_100692/miniconda3/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wwwdev.ebi.ac.uk', port=443): Max retries exceeded with url: /pdbe/aggregated-api/mappings/ensembl_to_pdb/ENSG00000130234 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shpc_100692/miniconda3/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/gget/main.py", line 1452, in main
    info_results = info(
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/gget/gget_info.py", line 250, in info
    pdb_ids = get_pdb_ids(ens_id)
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/gget/utils.py", line 495, in get_pdb_ids
    res = requests.get(ENS_TO_PDB_API + ens_id)
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/shpc_100692/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='wwwdev.ebi.ac.uk', port=443): Max retries exceeded with url: /pdbe/aggregated-api/mappings/ensembl_to_pdb/ENSG00000130234 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
```
Guess that occured because connection is not resultful as I'm in Asia?

Could you give me any direction?

**Comment by lauraluebbert** [comment]
Could you please give me your gget version (`gget -v`) and the exact command that led to the error? Does this happen every time you run the command?

**Comment by lauraluebbert** [comment]
This is the latest gget version, so that should be fine. It looks like there is an occasional problem with the connection to PDBe. I contacted them about it. Depending on which information you are interested in, you could use flag `--ensembl_only`  (e.g., `gget info -eo ENSG00000130234 ENST00000252519`) to return only the results from Ensembl. This will omit pinging the PDBe database. I will work on a solution that returns all of the results that were obtained successfully, even when one database returns an SSLError.
